name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Set environment variables
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
        echo "GCP_DATASET_NAME=${{ secrets.GCP_DATASET_NAME }}" >> $GITHUB_ENV
        echo "GCP_TABLE_NAME=${{ secrets.GCP_TABLE_NAME }}" >> $GITHUB_ENV

    - name: Add src to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/gcp-devops-project:latest .

    - name: Deploy to Google Cloud Run
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        SERVICE_NAME: gcp-devops-project
        IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/gcp-devops-project
      run: |
        gcloud auth activate-service-account --key-file=- <<< "${{ secrets.GCP_KEY }}"
        gcloud --quiet config set project $PROJECT_ID
        gcloud run deploy $SERVICE_NAME --image $IMAGE --platform managed --region europe-west8 --allow-unauthenticated